In [6]:
#creating 1-D array
import numpy as np
a=[1,2,3,4,5]
arr=np.array(a)
arr

array([1, 2, 3, 4, 5])

In [14]:
#creating 2-D array
b=[6,7,8,9,10]
arr=np.array([a,b])
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
#dtype

np.dtype(np.int32)

dtype('int32')

In [23]:
#Adding (arithmetic operation)
a=[1,2,3,4]
b=[3,4,6,6]
np.add(a,b)


array([ 4,  6,  9, 10])

In [24]:
#Subtracting (arithmetic operation)
np.subtract(a,b)

array([-2, -2, -3, -2])

In [25]:
#Multiplying (arithmetic operation)

np.multiply(a,b)

array([ 3,  8, 18, 24])

In [26]:
#dividing (arithmetic operation)
np.divide(a,b)


array([0.33333333, 0.5       , 0.5       , 0.66666667])

In [28]:
#dividing (arithmetic operation)
a=[1,2,0.43]
np.reciprocal(a)

array([1.       , 0.5      , 2.3255814])

In [29]:
#power (arithemetic operation)

np.power(a,2)

array([1.    , 4.    , 0.1849])

In [32]:
#basic indexing and slicing

a=[1,3,4,5,5,7,8,2,6,4,9,7,4,4]
a=np.array(a)
a[3:6]

array([5, 5, 7])

In [41]:
a[3:]


[4, 3, 5, 6, 5, 5, 6]

In [43]:
#important funtion in numpy

#arrange

np.arange(6)



array([0, 1, 2, 3, 4, 5])

In [44]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [45]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [46]:
#Zeros matrix

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
#ones matrix

np.ones((3,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
#random numbers

np.random.randint(0,10)

9

In [63]:
a=[5,45,3,5,3,344,6,89,5,7,775,3,3,2]

a=np.array(a)
a.max()

775

In [59]:
a.min()

3

In [60]:
a.argmax()

10

In [61]:
a.argmin()

2

In [64]:
a.reshape(2,7)

array([[  5,  45,   3,   5,   3, 344,   6],
       [ 89,   5,   7, 775,   3,   3,   2]])